"""Ports (interfaces) for use cases — dependency inversion.

Use cases depend on these Protocols, infra adapters implement them structurally
(duck typing). Keeps inner layers free of concrete infra import.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator
from datetime import datetime
from pathlib import Path
from typing import Any, Optional, Protocol, runtime_checkable

# ── Repositories ───────────────────────────────────────────────────────

@runtime_checkable
class UploadSessionRepositoryPort(Protocol):
    async def create(self, upload_session: Any) -> Any: ...
    async def get_by_id(self, upload_id: str) -> Optional[Any]: ...
    async def count_layers_referencing(self, upload_id: str) -> int: ...
    async def count_batches_referencing(self, upload_id: str) -> int: ...
    async def get_by_artifact_handoff(self, handoff_id: str) -> Optional[Any]: ...
    async def update_chunk_map(
        self,
        upload_id: str,
        chunk_index: int,
        chunk_bytes: int,
        uploaded_chunks: int,
        received_bytes: int,
    ) -> Any: ...
    async def mark_expired(self, upload_id: str) -> Any: ...
    async def mark_complete(self, upload_id: str, final_path: str) -> Any: ...
    async def set_status(self, upload_id: str, status: str, note: Optional[str] = None) -> Any: ...
    async def set_task_id(self, upload_id: str, task_id: str) -> Any: ...
    async def queue_import(self, upload_id: str, task_id: str, table_name: str) -> Any: ...
    async def set_import_status(self, upload_id: str, status: str, note: Optional[str] = None) -> Any: ...
    async def start_tiling(self, upload_id: str, task_id: str, progress: int = 0) -> Any: ...
    async def set_artifact_lease(self, upload_id: str, lease_id: Optional[str]) -> Any: ...
    async def delete(self, upload_id: str) -> bool: ...

@runtime_checkable
class SyncUploadSessionRepositoryPort(Protocol):
    def get_by_id(self, upload_id: str) -> Optional[Any]: ...
    def count_layers_referencing(self, upload_id: str) -> int: ...
    def count_batches_referencing(self, upload_id: str) -> int: ...
    def set_status(self, upload_id: str, status: str, note: Optional[str] = None) -> Any: ...
    def set_task_id(self, upload_id: str, task_id: str) -> Any: ...
    def set_import_status(self, upload_id: str, status: str, note: Optional[str] = None) -> Any: ...
    def update_import_progress(self, upload_id: str, task_id: str, progress: int) -> Any: ...
    def complete_import(self, upload_id: str) -> Any: ...

@runtime_checkable
class LayerRepositoryPort(Protocol):
    def list_all(self, *args: Any, **kwargs: Any) -> list[Any]: ...
    def paginate(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_by_id(self, layer_id: str) -> Optional[Any]: ...
    def create(self, layer: Any) -> Any: ...
    def update(self, layer: Any) -> Any: ...
    def code_exists(self, code: str) -> bool: ...
    def find_geoserver_layer_name(self, layer_id: str) -> Optional[str]: ...
    def delete(self, layer_id: str) -> bool: ...
    async def update_mbtiles(self, layer_id: str, path: str) -> Any: ...

@runtime_checkable
class SyncLayerRepositoryPort(Protocol):
    def get_by_id(self, layer_id: str) -> Optional[Any]: ...
    def create(self, layer: Any) -> Any: ...
    def update_progress(self, layer_id: str, progress: int) -> Any: ...
    def update_download_progress(self, layer_id: str, progress: int, status: str) -> Any: ...
    def get_download_progress(self, layer_id: str) -> Optional[tuple[int, str]]: ...
    def update_mbtiles(self, layer_id: str, path: str) -> Any: ...
    def list_all(self) -> list[Any]: ...
    def code_exists(self, code: str) -> bool: ...

@runtime_checkable
class ProjectRepositoryPort(Protocol):
    def unlink_layer(self, project_id: str, layer_id: str) -> Any: ...
    def create(self, project: Any) -> Any: ...
    def get_by_id(self, project_id: str) -> Optional[Any]: ...
    def list_all(self, *args: Any, **kwargs: Any) -> list[Any]: ...
    def update(self, project: Any) -> Any: ...
    def delete(self, project_id: str) -> bool: ...

@runtime_checkable
class FeatureRepositoryPort(Protocol):
    def create(self, feature: Any) -> Any: ...
    def get_by_id(self, feature_id: str) -> Optional[Any]: ...
    def list_by_project(self, project_id: str, *args: Any, **kwargs: Any) -> list[Any]: ...
    def update(self, feature: Any) -> Any: ...
    def delete(self, feature_id: str) -> bool: ...
    def delete_by_project(self, project_id: str) -> int: ...

@runtime_checkable
class SyncAnalysisResultRepositoryPort(Protocol):
    def get_by_id(self, result_id: str) -> Optional[Any]: ...
    def get_by_layer_id(self, layer_id: str) -> Optional[Any]: ...
    def create(self, result: Any) -> Any: ...
    def update(self, result: Any) -> Any: ...
    def delete(self, result_id: str) -> bool: ...
    def list_expired_ephemeral(self, deadline: datetime) -> list[Any]: ...

# ── Services / clients ─────────────────────────────────────────────────

@runtime_checkable
class FileServicePort(Protocol):
    async def save_upload(self, file: Any) -> tuple[Path, str]: ...

@runtime_checkable
class ChunkStoragePort(Protocol):
    def ensure_dir(self, session_id: str) -> None: ...
    def write_chunk(self, session_id: str, data: bytes, start_offset: int) -> None: ...
    def assemble_chunks(self, session_id: str, dest_path: Path) -> None: ...
    def cleanup_chunks(self, session_id: str) -> None: ...

@runtime_checkable
class UploadArtifactClientPort(Protocol):
    def acquire_lease(self, artifact_id: str, grant_id: str, reference: str) -> dict: ...
    def create_user_grant(self, artifact_id: str, authorization: str) -> str: ...
    def metadata(self, artifact_id: str) -> dict: ...
    def release_lease(self, artifact_id: str, lease_id: str) -> None: ...
    def materialize(self, artifact_id: str, filename: str) -> Iterator[Path]: ...

@runtime_checkable
class LegendRendererPort(Protocol):
    def is_stale(self, out_path: Path, fingerprint: Any) -> bool: ...
    def raster_fingerprint(self, source: Path) -> Any: ...
    def vector_fingerprint(self, style: Any) -> Any: ...
    def render_raster_legend(self, source: Path, out_path: Path, fingerprint: Any) -> None: ...
    def render_vector_legend(self, style: Any, out_path: Path, fingerprint: Any) -> None: ...

@runtime_checkable
class NominatimClientPort(Protocol):
    def forward(self, query: str, limit: int = 1) -> list[dict]: ...
    def reverse(self, lon: float, lat: float) -> Optional[dict]: ...

@runtime_checkable
class AnalysisExportServicePort(Protocol):
    def save_geojson(self, gdf: Any, result_id: str) -> str: ...
    def delete_result(self, file_path: str) -> None: ...
    def save_sources(self, sources: dict, result_id: str) -> None: ...
    def get_geojson_path(self, file_path: str) -> Optional[Path]: ...
    def export_shp_zip(self, file_path: str) -> Optional[Path]: ...

@runtime_checkable
class ReferenceSourcePort(Protocol):
    def load_reference(self, session: Any, layer: Any, settings: Any) -> tuple[Any, str]: ...
    def repair_geometry(self, frame: Any) -> Any: ...

@runtime_checkable
class AnalysisStoragePort(Protocol):
    def read_shapefile_archive(self, archive: Path, destination: Path, settings: Any) -> Any: ...
    def write_json(self, path: Path, value: Any) -> None: ...
    def read_json(self, path: Path) -> Any: ...
    def persist_result(self, source: Path, destination: Path) -> Path: ...
    def export_results(self, directory: Path, result: Any) -> None: ...

AnalysisTaskEnqueuer = Callable[..., Any]
