"""add shapefile import tracking

Revision ID: 0007
Revises: 0006_add_upload_artifact_ref
Create Date: 2026-08-28 07:27:55.598095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, None] = '0006_add_upload_artifact_ref'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS geodata"))
    op.add_column(
        'upload_sessions',
        sa.Column('import_status', sa.String(), nullable=False, server_default='not_applicable'),
    )
    op.add_column('upload_sessions', sa.Column('import_task_id', sa.String(), nullable=True))
    op.add_column('upload_sessions', sa.Column('import_error', sa.Text(), nullable=True))
    op.add_column('upload_sessions', sa.Column('import_table_name', sa.String(), nullable=True))
    op.add_column(
        'upload_sessions',
        sa.Column('import_processed_rows', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column(
        'upload_sessions',
        sa.Column('import_total_rows', sa.Integer(), nullable=False, server_default='0'),
    )
    op.add_column('upload_sessions', sa.Column('imported_row_count', sa.Integer(), nullable=True))
    op.add_column('upload_sessions', sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_sessions', 'imported_at')
    op.drop_column('upload_sessions', 'imported_row_count')
    op.drop_column('upload_sessions', 'import_total_rows')
    op.drop_column('upload_sessions', 'import_processed_rows')
    op.drop_column('upload_sessions', 'import_table_name')
    op.drop_column('upload_sessions', 'import_error')
    op.drop_column('upload_sessions', 'import_task_id')
    op.drop_column('upload_sessions', 'import_status')
    if op.get_bind().dialect.name == "postgresql":
        op.execute(sa.text("DROP SCHEMA IF EXISTS geodata CASCADE"))
    # ### end Alembic commands ###
