"""add reference analysis workspace

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-13 18:57:07.772864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_uploads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('geometry_types', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_uploads_expires_at'), 'analysis_uploads', ['expires_at'], unique=False)
    op.create_index(op.f('ix_analysis_uploads_owner_hash'), 'analysis_uploads', ['owner_hash'], unique=False)
    op.create_table('reference_analysis_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reference_config', sa.JSON(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('source_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['input_id'], ['analysis_uploads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('input_id')
    )
    op.create_index(op.f('ix_reference_analysis_jobs_expires_at'), 'reference_analysis_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_reference_analysis_jobs_owner_hash'), 'reference_analysis_jobs', ['owner_hash'], unique=False)
    op.create_index(op.f('ix_reference_analysis_jobs_status'), 'reference_analysis_jobs', ['status'], unique=False)
    op.create_table('active_analysis_sources',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['reference_analysis_jobs.id'], ),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_active_analysis_sources_layer_id'), 'active_analysis_sources', ['layer_id'], unique=False)
    op.create_table('analysis_references',
    sa.Column('layer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category_field', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layers.id'], ),
    sa.PrimaryKeyConstraint('layer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_references')
    op.drop_index(op.f('ix_active_analysis_sources_layer_id'), table_name='active_analysis_sources')
    op.drop_table('active_analysis_sources')
    op.drop_index(op.f('ix_reference_analysis_jobs_status'), table_name='reference_analysis_jobs')
    op.drop_index(op.f('ix_reference_analysis_jobs_owner_hash'), table_name='reference_analysis_jobs')
    op.drop_index(op.f('ix_reference_analysis_jobs_expires_at'), table_name='reference_analysis_jobs')
    op.drop_table('reference_analysis_jobs')
    op.drop_index(op.f('ix_analysis_uploads_owner_hash'), table_name='analysis_uploads')
    op.drop_index(op.f('ix_analysis_uploads_expires_at'), table_name='analysis_uploads')
    op.drop_table('analysis_uploads')
    # ### end Alembic commands ###
