"""sync layers table schema with models

Revision ID: b1e6a6bcc46d
Revises: 06152298d185
Create Date: 2026-05-18 01:09:17.255541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b1e6a6bcc46d'
down_revision: Union[str, None] = '06152298d185'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('code', sa.String(), nullable=True))
    op.add_column('layers', sa.Column('layer_type', sa.String(), nullable=False, server_default='tile'))
    op.add_column('layers', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('layers', sa.Column('is_visible', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('layers', sa.Column('opacity', sa.Float(), nullable=False, server_default='1.0'))
    op.add_column('layers', sa.Column('sorting', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('layers', sa.Column('file_metadata', sa.JSON(), nullable=True))
    op.alter_column('layers', 'upload_session_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('layers', 'upload_session_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('layers', 'file_metadata')
    op.drop_column('layers', 'sorting')
    op.drop_column('layers', 'opacity')
    op.drop_column('layers', 'is_visible')
    op.drop_column('layers', 'is_active')
    op.drop_column('layers', 'layer_type')
    op.drop_column('layers', 'code')
    # ### end Alembic commands ###
