# /etc/celery.conf

# Nama aplikasi Celery Anda
CELERY_APP="nama_project_anda"

# Path absolut ke direktori project (tempat file .env berada)
CELERYD_CHDIR="/home/user/nama_project_anda"

# Path ke binary Celery di dalam Virtual Environment
CELERY_BIN="/home/user/nama_project_anda/venv/bin/celery"

# Log dan PID
CELERYD_LOG_FILE="/var/log/celery/%n%I.log"
CELERYD_PID_FILE="/var/run/celery/%n.pid"

# Argumen tambahan
CELERYD_OPTS="--time-limit=300 --concurrency=4 --loglevel=INFO"