server {
    listen 80;
    server_name tileserver.co.id;

    # Logging
    access_log /var/log/nginx/tileserver.access.log;
    error_log /var/log/nginx/tileserver.error.log;
    location / {
            proxy_pass http://127.0.0.1:8050;

            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_request_buffering off;
            proxy_buffering off;
    }


    # Batasi referrer agar tidak bocor
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    # Content Security Policy (ketat)
    # add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; font-src 'self'; frame-ancestors 'none'; object-src 'none'; base-uri 'self'; form-action 'self'" always;
    # add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src'self' data:;" always;

    # MIME sniffing protection
    add_header X-Content-Type-Options "nosniff" always;

    # Clickjacking protection
    add_header X-Frame-Options "DENY" always;

    # XSS protection (untuk browser lama)
    add_header X-XSS-Protection "1; mode=block" always;

    # Batasi fitur API browser
    # add_header Permissions-Policy "geolocation=(), microphone=(), camera=(), payment=()" always;

    # HSTS (paksa HTTPS)
    #add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    client_max_body_size 20M;

    # Blok akses ke file sensitif
    location ~ /\.(ht|git|env) {
        deny all;
    }

    location /tiles/ {
        alias /docker_volume/docker_tileserver_media/_data/_data/; # ganti ini
        expires 30d;
    }
}